kind: Template
apiVersion: v1
labels:
  template: loki-template
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${LOKI_SERVICE_NAME}
      namespace: ${NAMESPACE}
      labels:
        app: loki
        chart: loki-0.16.0
        release: ${LOKI_SERVICE_NAME}
        heritage: Tiller
    data:
      loki.yaml: YXV0aF9lbmFibGVkOiBmYWxzZQpjaHVua19zdG9yZV9jb25maWc6CiAgbWF4X2xvb2tfYmFja19wZXJpb2Q6IDAKaW5nZXN0ZXI6CiAgY2h1bmtfYmxvY2tfc2l6ZTogMjYyMTQ0CiAgY2h1bmtfaWRsZV9wZXJpb2Q6IDNtCiAgY2h1bmtfcmV0YWluX3BlcmlvZDogMW0KICBsaWZlY3ljbGVyOgogICAgcmluZzoKICAgICAga3ZzdG9yZToKICAgICAgICBzdG9yZTogaW5tZW1vcnkKICAgICAgcmVwbGljYXRpb25fZmFjdG9yOiAxCmxpbWl0c19jb25maWc6CiAgZW5mb3JjZV9tZXRyaWNfbmFtZTogZmFsc2UKICByZWplY3Rfb2xkX3NhbXBsZXM6IHRydWUKICByZWplY3Rfb2xkX3NhbXBsZXNfbWF4X2FnZTogMTY4aApzY2hlbWFfY29uZmlnOgogIGNvbmZpZ3M6CiAgLSBmcm9tOiAiMjAxOC0wNC0xNSIKICAgIGluZGV4OgogICAgICBwZXJpb2Q6IDE2OGgKICAgICAgcHJlZml4OiBpbmRleF8KICAgIG9iamVjdF9zdG9yZTogZmlsZXN5c3RlbQogICAgc2NoZW1hOiB2OQogICAgc3RvcmU6IGJvbHRkYgpzZXJ2ZXI6CiAgaHR0cF9saXN0ZW5fcG9ydDogMzEwMApzdG9yYWdlX2NvbmZpZzoKICBib2x0ZGI6CiAgICBkaXJlY3Rvcnk6IC9kYXRhL2xva2kvaW5kZXgKICBmaWxlc3lzdGVtOgogICAgZGlyZWN0b3J5OiAvZGF0YS9sb2tpL2NodW5rcwp0YWJsZV9tYW5hZ2VyOgogIHJldGVudGlvbl9kZWxldGVzX2VuYWJsZWQ6IGZhbHNlCiAgcmV0ZW50aW9uX3BlcmlvZDogMAo=
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${LOKI_SERVICE_NAME}-headless
      namespace: ${NAMESPACE}
      labels:
        app: loki
        chart: loki-0.16.0
        release: ${LOKI_SERVICE_NAME}
        heritage: Tiller
    spec:
      clusterIP: None
      ports:
        - port: 3100
          protocol: TCP
          name: http-metrics
          targetPort: http-metrics
      selector:
        app: loki
        release: ${LOKI_SERVICE_NAME}
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${LOKI_SERVICE_NAME}
      namespace: ${NAMESPACE}
      labels:
        app: loki
        chart: loki-0.16.0
        release: ${LOKI_SERVICE_NAME}
        heritage: Tiller
      annotations:
        {}
    spec:
      type: ClusterIP
      ports:
        - port: 3100
          protocol: TCP
          name: http-metrics
          targetPort: http-metrics
      selector:
        app: loki
        release: ${LOKI_SERVICE_NAME}
  - apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: ${LOKI_SERVICE_NAME}
      namespace: ${NAMESPACE}
      labels:
        app: ${LOKI_SERVICE_NAME}
      annotations:
        our-awesome-metadata: "nothing to see here"
        prometheus.io/port: http-metrics
        prometheus.io/scrape: "true"
    spec:
      replicas: 1
      minReadySeconds: 0
      selector:
        matchLabels:
          app: ${LOKI_SERVICE_NAME}
      updateStrategy:
        type: RollingUpdate    
       
      containers:
        - name: loki
          image: "grafana/loki:v0.3.0"
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/loki/loki.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: "/data"
              subPath: 
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
            
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
            
          resources:
            {}
            
          securityContext:
            readOnlyRootFilesystem: true   
      template:
        metadata:
          labels:
            app: ${LOKI_SERVICE_NAME}
        spec:
          serviceAccountName: default   
parameters:
- description: The name of the OpenShift Service exposed for the database.
  displayName: Loki Service Name
  name: LOKI_SERVICE_NAME
  required: true
  value: loki
- description: The namespace this templated is deployed into.
  displayName: Namespace
  name: NAMESPACE
  value: openshift
